# Generated by Django 5.1.4 on 2025-01-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_integer_field', models.IntegerField()),
                ('my_date_field', models.DateField()),
            ],
        ),
    ]
