# Generated by Django 5.1.4 on 2025-02-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('malumot', models.IntegerField(verbose_name='Malumot kiriting')),
                ('yosh', models.DateField(verbose_name='Yoshingizni kiriting')),
            ],
        ),
        migrations.CreateModel(
            name='name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('malumot', models.IntegerField(verbose_name='Malumot kiriting')),
                ('yosh', models.DateField(verbose_name='Yoshingizni kiriting')),
            ],
        ),
    ]
